### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by picsi** [theblackwidower/KanaQuiz#1]
It'd be pretty neat to have this on F-Droid, as there are few Japanese studying materials there: https://f-droid.org/

**Comment by theblackwidower** [comment]
I'm not sure what the standard submission protocol is for F-Droid, but I believe I began the process here: https://gitlab.com/fdroid/rfp/issues/491

If anyone wishes to help out on this front, I'm all for it.

**Comment by theblackwidower** [comment]
By the way, it's been added.

https://f-droid.org/packages/com.noprestige.kanaquiz/

**Comment by picsi** [comment]
Great work, thanks a lot!

**Comment by oxr463** [comment]
Bump reqested on F-Droid, (See: https://gitlab.com/fdroid/fdroiddata/issues/1762).

**Comment by theblackwidower** [comment]
It's annoying that keeps having to be done.

**Comment by oxr463** [comment]
I'll do my best to catch it when I see it, but this is definitely on the F-Droid side.
