### ISSUE TITLE
Status of translations

### ISSUE THREAD

**Issue by Zenahr** [theblackwidower/KanaQuiz#14]
What is the status of language support of the app? Or rather, what localizations would be nice to have? I could provide a german translation and perform the pull-request for it.
(edit: fixed typo)

**Comment by theblackwidower** [comment]
We could certainly use a German translation. So far, the app is only available in English, and there are currently incomplete translations to Spanish and Catalan. So anything you can provide would be helpful.

**Comment by Zenahr** [comment]
Noted!
