### ISSUE TITLE
[Bug] Different Quiz Generation when Rotating Screen

### ISSUE THREAD

**Issue by ditokp** [theblackwidower/KanaQuiz#5]
I try rotating screen to make word more fit in quick reference. But in the quiz section, when I rotate the screen, the word is change.

Example:
In portrait word "a", but in landscape word "iie", and when rotate again the word is change to other word.

Screenshot:

Before:

![](https://i.imgur.com/cmCgZQl.png)

After:

![](https://i.imgur.com/ynXYW5T.png)

My device:
Advan i4D

**Comment by theblackwidower** [comment]
Yeah, this is a known issue. [Here's proof.](https://github.com/theblackwidower/KanaQuiz/blob/d069a75c452ed4807dfe0819a607d16c2be8521d/app/src/main/java/com/noprestige/kanaquiz/quiz/MainQuiz.java#L108)

I had moved it to the back burner. But I guess it's more urgent then I thought. You could consider it a feature. I don't like that question--Rotate!

I'll see if I can add a fix to the next update. 

By the way, you don't have to worry about screenshots. I know what you're talking about. But I guess this is an indication I need to write up an issue template.

**Comment by ditokp** [comment]
Thank you for reading my issue & understand my talk

**Comment by theblackwidower** [comment]
Okay. Your screenshot showed another bug that you probably didn't notice, but there is a line of text there that is basically invisible, and I want to know why. You mind opening another issue for that? Are you running special themeing apps to change the fonts and colours? Because I'll need to reproduce this in the emulator. It's really bugging me because I thought I secured against this very issue.

**Comment by ditokp** [comment]
I'm really sorry, I will make a new issue after school time because my school WiFi is so slow

**Comment by ditokp** [comment]
I'm really sorry, I will make a new issue after school time because my school WiFi is so slow

**Comment by theblackwidower** [comment]
No need to apologize. That's my job.

**Comment by theblackwidower** [comment]
Implemented a fix. Will be in the next release.
